# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dynbps',
                'doc_host': 'https://josephrilling.github.io',
                'git_url': 'https://github.com/josephrilling/dynbps',
                'lib_path': 'dynbps'},
  'syms': {'dynbps.core': {'dynbps.core.foo': ('core.html#foo', 'dynbps/core.py')}}}
